version: '3.8'
services:
  shell:
    build:
      context: ./
    image: playground:latest
    command: [ ]
    entrypoint: [ ]
    depends_on:
      - db
      - redis
      - celery
    volumes:
      - ./:/src
  db:  # Port 5432
    image: mdillon/postgis:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: playground
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 5432:5432
  redis:  # Port 6379
    image: redis:7-alpine
    restart: always
  celery:
    restart: always
    build:
      context: ./
    volumes:
      - ./:/src
    command: celery -A dhp worker -l info

volumes:
  db_data:
