"""Initialize data, data_edge tables

Revision ID: 48f55a36b7b1
Revises:
Create Date: 2022-06-21 23:08:18.093973-07:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "48f55a36b7b1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("_data_file", sa.String(length=260), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_edge",
        sa.Column("source_data_id", postgresql.UUID(), nullable=False),
        sa.Column("derived_data_id", postgresql.UUID(), nullable=False),
        sa.Column("extra_data", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["derived_data_id"],
            ["data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_data_id"],
            ["data.id"],
        ),
        sa.PrimaryKeyConstraint("source_data_id", "derived_data_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_edge")
    op.drop_table("data")
    # ### end Alembic commands ###
