"""empty message

Revision ID: 2926d49440b9
Revises: 
Create Date: 2022-06-12 15:13:38.443351-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2926d49440b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('_data_file', sa.String(length=260), nullable=True),
    sa.Column('_data_io', sa.Enum('PANDAS_HDF', name='dataio'), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_edge',
    sa.Column('source_data', postgresql.UUID(), nullable=False),
    sa.Column('derived_data', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['derived_data'], ['data.id'], ),
    sa.ForeignKeyConstraint(['source_data'], ['data.id'], ),
    sa.PrimaryKeyConstraint('source_data', 'derived_data')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_edge')
    op.drop_table('data')
    # ### end Alembic commands ###
