"""Initialize data, data_edge tables


Revision ID: 5af9999ae324
Revises:
Create Date: 2022-06-24 21:11:10.939769-07:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5af9999ae324"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("_type", sa.String(length=50), nullable=True),
        sa.Column("data", sa.PickleType(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_deleted", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_edge",
        sa.Column("source_data_id", postgresql.UUID(), nullable=False),
        sa.Column("derived_data_id", postgresql.UUID(), nullable=False),
        sa.Column("extra_data", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ["derived_data_id"],
            ["data.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_data_id"],
            ["data.id"],
        ),
        sa.PrimaryKeyConstraint("source_data_id", "derived_data_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_edge")
    op.drop_table("data")
    # ### end Alembic commands ###
