"""Added account table

Revision ID: 7cccd29af166
Revises:
Create Date: 2022-06-08 23:54:12.789832-07:00

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7cccd29af166"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "base_data",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("_data_file", sa.String(length=260), nullable=True),
        sa.Column("_data_io", sa.Enum("PANDAS_HDF", name="dataio"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("base_data")
    # ### end Alembic commands ###
